import type { ScriptFormatDefinition } from "./types";

/**
 * Catálogo configurável de formatos de roteiro.
 * Dados puros — sem lógica de UI nem JSX.
 */
export const SCRIPT_FORMATS: ScriptFormatDefinition[] = [
  // ─── UGC Real ───────────────────────────────────────────────────────────────
  {
    id: "ugc_real_talking",
    name: "UGC real falando com a câmera",
    shortDescription: "Creator apresenta o produto de forma natural, olhando para a câmera.",
    fullDescription:
      "Formato de maior confiança do TikTok Shop. Uma pessoa real apresenta, demonstra e recomenda o produto de forma autêntica. O espectador sente que está recebendo uma dica de um amigo, não assistindo a um comercial. Ideal para produtos que enfrentam ceticismo ou têm benefícios que precisam ser explicados.",
    category: "ugc",
    trendStatus: "proven",
    bestFor: [
      "Suplementos",
      "Beleza",
      "Perfumes",
      "Produtos que precisam de confiança",
      "Produtos com objeções",
      "Produtos masculinos",
      "Produtos de ticket alto",
      "Skincare",
      "Saúde",
    ],
    avoidFor: [
      "Produtos sem demonstração visual",
      "Quando o criador não tem o produto físico",
      "Produtos de baixíssimo ticket que dependem de volume",
    ],
    requiredInputs: ["Produto físico", "Pessoa real", "Copy validada"],
    supportsAI: false,
    requiresRealProduct: true,
    requiresRealPerson: true,
    supportsNoSpeak: false,
    difficulty: "low",
    trustLevel: 5,
    complianceRisk: "medium",
    veoCompatibility: "partial",
    defaultDuration: 30,
    sceneStructure: ["Gancho", "Dor ou situação", "Demonstração", "Benefício", "Prova", "CTA"],
    promptRules: [
      "Person speaks directly to camera in natural Brazilian Portuguese",
      "Product must be held or visible throughout",
      "Authentic home or lifestyle setting",
      "Natural lighting, handheld camera feel",
      "Genuine facial expressions, no theatrical performance",
    ],
    negativePromptRules: [
      "no professional studio lighting",
      "no teleprompter look",
      "no scripted stiffness",
      "no fake smiles",
      "no invented medical claims",
      "no before-and-after fabrication",
    ],
    badges: ["proven_trend", "high_trust", "high_conversion"],
    warningWhenNoPhysicalProduct: true,
  },

  // ─── UGC Híbrido com IA ──────────────────────────────────────────────────────
  {
    id: "ugc_hybrid_ai",
    name: "UGC híbrido com IA",
    shortDescription: "Combina cenas reais com complementos gerados por IA.",
    fullDescription:
      "Abre com pessoa ou mãos reais, incluindo cenas ilustrativas criadas por IA para enriquecer a narrativa. Mantém confiança e permite produzir em escala sem gravar tudo do zero. Recomendado por padrão porque equilibra autenticidade com eficiência de produção.",
    category: "ugc",
    trendStatus: "rising",
    bestFor: [
      "Produção em escala",
      "Suplementos",
      "Beleza",
      "Skincare",
      "Produtos com benefícios que não são visíveis",
      "Quando o criador tem o produto mas precisa de cenas adicionais",
    ],
    avoidFor: [
      "Produtos regulados que não podem usar IA para simular resultados",
      "Quando o criador não tem nenhuma cena real disponível",
    ],
    requiredInputs: ["Produto físico (parcial)", "Cenas reais de abertura", "Geração IA para complemento"],
    supportsAI: true,
    requiresRealProduct: true,
    requiresRealPerson: true,
    supportsNoSpeak: false,
    difficulty: "medium",
    trustLevel: 4,
    complianceRisk: "medium",
    veoCompatibility: "full",
    defaultDuration: 35,
    sceneStructure: [
      "Abertura com pessoa real",
      "Close real do produto",
      "Cena ilustrativa IA",
      "Retorno ao produto real",
      "CTA real",
    ],
    promptRules: [
      "Clearly distinguish real scenes from AI-generated scenes",
      "AI scenes must not fabricate product effects or results",
      "Real person scenes anchor identity and trust",
      "Mark AI-significant content when publishing",
    ],
    negativePromptRules: [
      "no invented results",
      "no fake testimonials",
      "no simulated medical expertise",
      "no AI-fabricated before-after",
    ],
    badges: ["ai_compatible", "high_conversion"],
  },

  // ─── Manequim de IA na esteira ───────────────────────────────────────────────
  {
    id: "ai_treadmill_mannequin",
    name: "Manequim de IA caminhando na esteira",
    shortDescription: "Personagem ou manequim de IA caminhando enquanto apresenta múltiplos looks.",
    fullDescription:
      "Formato emergente internacional especialmente eficaz para moda. Um manequim ou personagem gerado por IA caminha continuamente em uma esteira, com trocas de look sincronizadas. Câmera fixa, corpo inteiro, mesmo personagem e cenário durante todo o vídeo. Permite mostrar várias cores e estilos de forma visualmente atraente.",
    category: "fashion_ai",
    trendStatus: "emerging",
    bestFor: [
      "Calças",
      "Vestidos",
      "Camisetas",
      "Conjuntos",
      "Moda masculina",
      "Moda fitness",
      "Bolsas",
      "Relógios",
      "Óculos",
      "Tênis",
      "Acessórios vestíveis",
    ],
    avoidFor: [
      "Suplementos",
      "Cosméticos que precisam de aplicação",
      "Produtos que exigem demonstração funcional real",
      "Produtos regulados",
      "Produtos cujo tamanho possa ser representado incorretamente",
    ],
    requiredInputs: ["Fotos do produto", "Geração IA", "Descrição do personagem"],
    supportsAI: true,
    requiresRealProduct: false,
    requiresRealPerson: false,
    supportsNoSpeak: true,
    difficulty: "high",
    trustLevel: 2,
    complianceRisk: "low",
    veoCompatibility: "full",
    defaultDuration: 32,
    sceneStructure: [
      "Estabelecimento — personagem e look inicial",
      "Troca de look 1",
      "Troca de look 2",
      "Troca de look 3 + CTA",
    ],
    promptRules: [
      "Fixed camera, full body shot, same character throughout",
      "Treadmill walking at consistent speed",
      "Each scene must redeclare: character, outfit, scenario, camera, lighting, movement, product, transition moment, restrictions",
      "Natural loop possible",
      "Can show color variants",
    ],
    negativePromptRules: [
      "no character change",
      "no face change",
      "no body change",
      "no scenario change",
      "no treadmill change",
      "no framing change",
      "no pattern alteration",
      "no color alteration",
      "no fit alteration",
      "no clothing phasing through body",
      "no extra fingers",
      "no extra arms",
      "no extra legs",
      "no melting fabric",
      "no floating products",
      "no camera shake",
      "no unsolicited zoom",
      "no deformed text",
      "no invented logos",
    ],
    badges: ["emerging_international", "ai_compatible", "fashion_recommended", "no_speak"],
    treadmillVariants: [
      { id: "color_catalog", name: "Catálogo de cores", description: "Mostra o mesmo modelo em cores diferentes" },
      { id: "three_ways", name: "Três maneiras de usar", description: "Stylings diferentes para a mesma peça" },
      { id: "basic_vs_complete", name: "Look básico × completo", description: "Evolução do look em cena" },
      { id: "male_minimalist", name: "Masculino minimalista", description: "Estética limpa para moda masculina" },
      { id: "fitness", name: "Fitness", description: "Looks de treino em sequência" },
      { id: "choose_favorite", name: "Escolha seu favorito", description: "Estimula votação nos comentários" },
      { id: "casual_to_elegant", name: "Do casual ao elegante", description: "Progressão de estilo" },
    ],
  },

  // ─── Modelo real na esteira ──────────────────────────────────────────────────
  {
    id: "real_treadmill_model",
    name: "Modelo real caminhando na esteira",
    shortDescription: "Versão gravada com pessoa real. Maior fidelidade, menor risco de inconsistência.",
    fullDescription:
      "Versão do formato de esteira usando modelo real gravado. Pode receber cortes, transições e alterações de roupa na edição. Menor risco de artefatos de IA e maior confiança de representação do produto real.",
    category: "fashion_ai",
    trendStatus: "steady",
    bestFor: ["Roupas", "Calçados", "Acessórios", "Moda premium", "Moda fitness", "Looks completos"],
    avoidFor: ["Quando não há modelo disponível", "Produtos sem relação com moda ou acessórios"],
    requiredInputs: ["Modelo real", "Produto físico", "Espaço para gravação", "Edição de vídeo"],
    supportsAI: false,
    requiresRealProduct: true,
    requiresRealPerson: true,
    supportsNoSpeak: true,
    difficulty: "high",
    trustLevel: 4,
    complianceRisk: "low",
    veoCompatibility: "limited",
    defaultDuration: 30,
    sceneStructure: ["Look 1 — completo", "Look 2 — ângulo diferente", "Look 3 — close detalhe", "CTA"],
    promptRules: [
      "Real model footage, consistent identity",
      "Edit transitions between looks",
      "Maintain product visibility",
    ],
    negativePromptRules: ["no AI artifacts", "no misrepresentation of fit"],
    badges: ["proven_trend", "fashion_recommended", "low_risk"],
  },

  // ─── Troca de looks com IA ───────────────────────────────────────────────────
  {
    id: "ai_outfit_transition",
    name: "Troca de looks com IA",
    shortDescription: "Personagem parada ou em movimento com trocas de roupa sincronizadas.",
    fullDescription:
      "Personagem parada, girando, andando em direção à câmera ou realizando uma transição enquanto as roupas mudam. Múltiplos estilos de transição disponíveis: giro do vestido, mudança por estalo, por movimento da mão, ao passar na frente da câmera, sincronizada com batida, ou por entrada e saída de quadro.",
    category: "fashion_ai",
    trendStatus: "emerging",
    bestFor: [
      "Vestidos",
      "Conjuntos",
      "Roupas femininas",
      "Roupas com movimento de tecido",
      "Coleções com várias cores",
    ],
    avoidFor: [
      "Produtos não vestíveis",
      "Suplementos",
      "Eletrônicos",
    ],
    requiredInputs: ["Fotos do produto", "Geração IA", "Descrição de transição desejada"],
    supportsAI: true,
    requiresRealProduct: false,
    requiresRealPerson: false,
    supportsNoSpeak: true,
    difficulty: "high",
    trustLevel: 2,
    complianceRisk: "low",
    veoCompatibility: "full",
    defaultDuration: 24,
    sceneStructure: ["Personagem estabelecida", "Transição 1", "Transição 2", "Look final + CTA"],
    promptRules: [
      "Smooth outfit transition, physics-realistic fabric",
      "Consistent character identity across transitions",
      "Transition type must be specified in each scene prompt",
    ],
    negativePromptRules: [
      "no character change",
      "no face change",
      "no glitching",
      "no fabric melting",
      "no body distortion",
    ],
    badges: ["emerging_international", "ai_compatible", "fashion_recommended", "no_speak"],
  },

  // ─── No-speak visual ──────────────────────────────────────────────────────────
  {
    id: "silent_visual_demo",
    name: "No-speak visual",
    shortDescription: "Demonstração visual com música, sons satisfatórios e textos curtos. Sem fala.",
    fullDescription:
      "Vídeo sem fala usando música, sons satisfatórios, textos curtos na tela, demonstração real do produto em uso, setas, zoom e comparação visual. Não é uma apresentação de slides — deve ter movimento constante e produto sempre em uso. Eficaz para produtos com resultado visual imediato.",
    category: "no_speak",
    trendStatus: "steady",
    bestFor: [
      "Produtos de limpeza",
      "Organizadores",
      "Utensílios",
      "Produtos com textura",
      "Roupas (resultado visual)",
      "Produtos de baixo ticket",
      "Gadgets",
    ],
    avoidFor: [
      "Suplementos (precisam de confiança)",
      "Produtos com objeções complexas",
      "Produtos que exigem explicação técnica",
    ],
    requiredInputs: ["Produto físico ou fotos de alta qualidade", "Música", "Textos concisos"],
    supportsAI: true,
    requiresRealProduct: false,
    requiresRealPerson: false,
    supportsNoSpeak: true,
    difficulty: "low",
    trustLevel: 2,
    complianceRisk: "low",
    veoCompatibility: "full",
    defaultDuration: 20,
    sceneStructure: ["Gancho visual", "Demonstração principal", "Resultado", "CTA visual"],
    promptRules: [
      "No spoken dialogue, music-driven pacing",
      "Product in motion throughout",
      "On-screen text must be short and readable",
      "Satisfying sounds when applicable",
    ],
    negativePromptRules: ["no static slides", "no talking heads", "no invented results"],
    badges: ["low_risk", "ai_compatible", "no_speak"],
  },

  // ─── Problema e solução ───────────────────────────────────────────────────────
  {
    id: "problem_solution",
    name: "Problema e solução",
    shortDescription: "Mostra o problema real, apresenta o produto como solução e demonstra o resultado.",
    fullDescription:
      "Estrutura clássica de alta conversão. O vídeo começa mostrando um problema real e a frustração associada, depois apresenta o produto, demonstra a solução em uso e fecha com o resultado e CTA.",
    category: "demonstration",
    trendStatus: "proven",
    bestFor: [
      "Limpeza",
      "Organização",
      "Cozinha",
      "Eletrônicos",
      "Utilidades",
      "Acessórios",
      "Produtos de cuidado pessoal",
    ],
    avoidFor: ["Produtos que não resolvem um problema claro", "Produtos de puro desejo ou status"],
    requiredInputs: ["Produto físico", "Demonstração do problema", "Demonstração da solução"],
    supportsAI: true,
    requiresRealProduct: true,
    requiresRealPerson: false,
    supportsNoSpeak: true,
    difficulty: "low",
    trustLevel: 4,
    complianceRisk: "low",
    veoCompatibility: "full",
    defaultDuration: 30,
    sceneStructure: [
      "Problema real",
      "Frustração",
      "Apresentação do produto",
      "Demonstração da solução",
      "Resultado",
      "CTA",
    ],
    promptRules: [
      "Show real problem clearly before product introduction",
      "Product must genuinely solve the shown problem",
      "Result must be achievable and not exaggerated",
    ],
    negativePromptRules: ["no fabricated results", "no exaggerated before-after", "no health claims without basis"],
    badges: ["proven_trend", "high_conversion", "low_risk"],
  },

  // ─── Demonstração satisfatória ────────────────────────────────────────────────
  {
    id: "satisfying_demo",
    name: "Demonstração satisfatória",
    shortDescription: "Closes, sons, cortes rápidos e resultado progressivo que geram retenção.",
    fullDescription:
      "Formato de alta retenção que explora o prazer visual e auditivo da demonstração. Indicado para produtos que produzem resultado visual imediato. Usa closes extremos, sons satisfatórios, cortes rápidos e resultado progressivo para manter a atenção.",
    category: "demonstration",
    trendStatus: "proven",
    bestFor: [
      "Lavadoras portáteis",
      "Vaporizadores",
      "Limpadores",
      "Removedores de manchas",
      "Organizadores",
      "Utensílios de cozinha",
      "Produtos com textura",
      "Produtos que produzem resultado visual",
    ],
    avoidFor: ["Produtos intangíveis", "Suplementos", "Perfumes"],
    requiredInputs: ["Produto físico", "Gravação de demonstração real"],
    supportsAI: false,
    requiresRealProduct: true,
    requiresRealPerson: false,
    supportsNoSpeak: true,
    difficulty: "medium",
    trustLevel: 4,
    complianceRisk: "low",
    veoCompatibility: "full",
    defaultDuration: 25,
    sceneStructure: ["Gancho visual", "Close do produto", "Demonstração em uso", "Resultado progressivo", "CTA"],
    promptRules: [
      "Extreme close-ups of product in action",
      "Satisfying sound design",
      "Quick cuts between stages",
      "Progressive visual result throughout",
    ],
    negativePromptRules: ["no static shots", "no fake results", "no exaggerated transformations"],
    badges: ["proven_trend", "high_conversion", "low_risk"],
  },

  // ─── Aplicação diante da câmera ───────────────────────────────────────────────
  {
    id: "apply_on_camera",
    name: "Aplicação diante da câmera",
    shortDescription: "Aplicação fiel do produto diante da câmera. Skincare, maquiagem, capilares.",
    fullDescription:
      "A aplicação do produto acontece em frente à câmera de forma fiel ao uso real. Não inventa resultados. Foco na textura, espalhamento, absorção e sensação. Para produtos de beleza onde ver a aplicação é o principal argumento de compra.",
    category: "demonstration",
    trendStatus: "proven",
    bestFor: [
      "Skincare",
      "Maquiagem",
      "Produtos capilares",
      "Perfume",
      "Produtos corporais",
      "Balm em bastão",
      "Pads",
      "Séruns",
      "Cremes",
    ],
    avoidFor: ["Produtos sem aplicação visual", "Suplementos internos", "Eletrônicos"],
    requiredInputs: ["Produto físico", "Pessoa para aplicação", "Iluminação adequada"],
    supportsAI: false,
    requiresRealProduct: true,
    requiresRealPerson: true,
    supportsNoSpeak: false,
    difficulty: "low",
    trustLevel: 5,
    complianceRisk: "medium",
    veoCompatibility: "partial",
    defaultDuration: 30,
    sceneStructure: [
      "Gancho visual (produto na mão)",
      "Preparação/apresentação",
      "Aplicação — passo a passo",
      "Resultado imediato",
      "CTA",
    ],
    promptRules: [
      "Application must match actual product use instructions",
      "Do not fabricate results or skin changes",
      "Show texture and consistency accurately",
      "Authentic skin reaction, not filtered",
    ],
    negativePromptRules: [
      "no AI-fabricated skin transformation",
      "no filter-enhanced results",
      "no invented medical effect",
      "no before-after without real evidence",
    ],
    badges: ["proven_trend", "beauty_recommended", "high_trust", "compliance_attention"],
    warningWhenNoPhysicalProduct: true,
  },

  // ─── Rotina em etapas ─────────────────────────────────────────────────────────
  {
    id: "routine_stack",
    name: "Rotina em etapas",
    shortDescription: "Apresenta o produto como parte de uma rotina com passos claros.",
    fullDescription:
      "Ideal para kits, combos e produtos que fazem parte de uma rotina. A estrutura mostra passo 1, passo 2, passo 3 e o resultado ou sensação final, seguido de CTA do kit. Cria desejo pelo conjunto completo.",
    category: "demonstration",
    trendStatus: "rising",
    bestFor: [
      "Kits de skincare",
      "Kits capilares",
      "Rotina de sono",
      "Suplementos",
      "Grooming masculino",
      "Combos",
      "Produtos complementares",
    ],
    avoidFor: ["Produto único sem relação com rotina", "Produtos de uso eventual"],
    requiredInputs: ["Produto físico", "Rotina definida", "Espaço para demonstração"],
    supportsAI: true,
    requiresRealProduct: true,
    requiresRealPerson: false,
    supportsNoSpeak: false,
    difficulty: "low",
    trustLevel: 4,
    complianceRisk: "medium",
    veoCompatibility: "full",
    defaultDuration: 35,
    sceneStructure: ["Gancho", "Passo 1", "Passo 2", "Passo 3", "Resultado/sensação final", "CTA do kit"],
    promptRules: [
      "Each step must be clearly numbered or labeled",
      "Products from the kit must all appear",
      "Show routine as achievable and pleasant",
    ],
    negativePromptRules: ["no invented health results", "no guarantee language", "no fake testimonials"],
    badges: ["kit_recommended", "beauty_recommended", "male_audience"],
  },

  // ─── Antes e depois controlado ────────────────────────────────────────────────
  {
    id: "before_after_proof",
    name: "Antes e depois controlado",
    shortDescription: "Antes e depois com resultado real e verificável. Alerta obrigatório.",
    fullDescription:
      "Permitido apenas quando houver resultado real e verificável. Exige alerta automático de que não foram usados filtros ou IA para fabricar o resultado. Quando necessário, inclui aviso de que os resultados podem variar. Nunca gera transformação milagrosa.",
    category: "demonstration",
    trendStatus: "steady",
    bestFor: [
      "Produtos de limpeza (resultado imediato)",
      "Organização (resultado visual)",
      "Produtos capilares (resultado real documentado)",
    ],
    avoidFor: [
      "Suplementos",
      "Produtos de emagrecimento",
      "Saúde regulada",
      "Qualquer produto onde o resultado varia muito ou não é verificável",
    ],
    requiredInputs: ["Fotos reais antes e depois", "Resultado documentado", "Produto físico"],
    supportsAI: false,
    requiresRealProduct: true,
    requiresRealPerson: false,
    supportsNoSpeak: true,
    difficulty: "medium",
    trustLevel: 4,
    complianceRisk: "high",
    veoCompatibility: "limited",
    defaultDuration: 25,
    sceneStructure: ["Situação antes (real)", "Aplicação ou uso", "Resultado após (real)", "CTA"],
    promptRules: [
      "Before state must be authentic, not staged",
      "After state must reflect genuine achievable result",
      "Must include: 'Resultados podem variar'",
      "Must NOT use AI or filters to enhance after state",
    ],
    negativePromptRules: [
      "no filter enhancement",
      "no AI-fabricated result",
      "no miracle transformation",
      "no exaggerated claims",
    ],
    badges: ["compliance_attention", "requires_physical_product", "low_risk"],
    warningWhenNoPhysicalProduct: true,
  },

  // ─── Comparação e escolha ─────────────────────────────────────────────────────
  {
    id: "comparison_choice",
    name: "Comparação e escolha",
    shortDescription: "Estimula comentários com comparações entre versões, cores ou modelos.",
    fullDescription:
      "Formato interativo que estimula comentários sem depender de promessas exageradas. Apresenta variações do produto lado a lado e convida o espectador a escolher sua favorita. Ideal para produtos com múltiplas opções.",
    category: "comparison",
    trendStatus: "proven",
    bestFor: [
      "Produtos com variações de cor",
      "Produtos com variações de tamanho",
      "Fragrâncias",
      "Sabores",
      "Moda",
      "Beleza",
    ],
    avoidFor: ["Produto único sem variações", "Produtos que não se prestam a comparação visual"],
    requiredInputs: ["Ao menos 2 variações do produto", "Fotos ou vídeos de cada opção"],
    supportsAI: true,
    requiresRealProduct: false,
    requiresRealPerson: false,
    supportsNoSpeak: true,
    difficulty: "low",
    trustLevel: 3,
    complianceRisk: "low",
    veoCompatibility: "full",
    defaultDuration: 20,
    sceneStructure: ["Apresentação da questão", "Opção A", "Opção B", "Convite ao comentário + CTA"],
    promptRules: [
      "Show each option fairly, no preference bias in visuals",
      "Comparison question must be clear",
      "Encourage comment engagement naturally",
    ],
    negativePromptRules: ["no fake reviews", "no biased comparison", "no invented specs"],
    badges: ["proven_trend", "low_risk", "ai_compatible"],
  },

  // ─── Reação e teste honesto ───────────────────────────────────────────────────
  {
    id: "honest_reaction",
    name: "Reação e teste honesto",
    shortDescription: "Reação genuína ao produto. Não finge experiência pessoal inexistente.",
    fullDescription:
      "Captura a reação genuína de alguém experimentando o produto pela primeira vez. Especialmente eficaz para alimentos, bebidas, fragrâncias e produtos de textura. O script nunca pode fingir uma experiência pessoal que não ocorreu. Quando o produto não está fisicamente disponível, o sistema não gera frases como 'Eu testei'.",
    category: "ugc",
    trendStatus: "rising",
    bestFor: [
      "Alimentos",
      "Bebidas",
      "Perfumes",
      "Produtos com sabores",
      "Produtos de textura diferente",
      "Caixas variadas",
      "Produtos importados",
    ],
    avoidFor: [
      "Quando o criador não tem o produto fisicamente",
      "Produtos regulados que exigem resultado clínico",
    ],
    requiredInputs: ["Produto físico disponível para teste", "Gravação da reação real"],
    supportsAI: false,
    requiresRealProduct: true,
    requiresRealPerson: true,
    supportsNoSpeak: false,
    difficulty: "low",
    trustLevel: 5,
    complianceRisk: "medium",
    veoCompatibility: "limited",
    defaultDuration: 30,
    sceneStructure: ["Apresentação do produto", "Momento do teste", "Reação genuína", "Comentário honesto", "CTA"],
    promptRules: [
      "Reaction must be authentic to real experience",
      "If no physical product available, never write 'I tested it' or 'I use it'",
      "Honest assessment, including mild negatives if any",
    ],
    negativePromptRules: [
      "no scripted fake reactions",
      "no simulated personal experience",
      "no invented taste or scent descriptions without real basis",
    ],
    badges: ["high_trust", "requires_physical_product"],
    warningWhenNoPhysicalProduct: true,
  },

  // ─── Unboxing e descoberta ────────────────────────────────────────────────────
  {
    id: "unboxing_discovery",
    name: "Unboxing e descoberta",
    shortDescription: "Abre o produto ao vivo, revelando conteúdo e criando antecipação.",
    fullDescription:
      "Ideal para kits, combos, caixas e presentes. A câmera registra a abertura da embalagem, revelando progressivamente o conteúdo. Cria antecipação natural e mostra o valor do produto completo.",
    category: "ugc",
    trendStatus: "steady",
    bestFor: [
      "Kits",
      "Combos",
      "Caixas surpresa",
      "Presentes",
      "Produtos colecionáveis",
      "Caixas de sabores",
      "Rotinas completas",
    ],
    avoidFor: ["Produto único sem embalagem especial", "Produtos digitais"],
    requiredInputs: ["Produto físico com embalagem", "Gravação da abertura"],
    supportsAI: false,
    requiresRealProduct: true,
    requiresRealPerson: false,
    supportsNoSpeak: false,
    difficulty: "low",
    trustLevel: 4,
    complianceRisk: "low",
    veoCompatibility: "partial",
    defaultDuration: 30,
    sceneStructure: ["Embalagem fechada (gancho)", "Abertura", "Revelação dos itens", "Destaque do item principal", "CTA"],
    promptRules: [
      "Show genuine unboxing progression",
      "Each item in kit must be visible",
      "Authentic excitement, not theatrical",
    ],
    negativePromptRules: ["no staged unboxing with fake surprise", "no invented kit items"],
    badges: ["kit_recommended", "proven_trend", "low_risk", "requires_physical_product"],
    warningWhenNoPhysicalProduct: true,
  },

  // ─── Storytelling de descoberta ───────────────────────────────────────────────
  {
    id: "discovery_story",
    name: "Storytelling de descoberta",
    shortDescription: "Narrativa de situação cotidiana que leva naturalmente ao produto.",
    fullDescription:
      "O vídeo começa com uma situação cotidiana relatable, uma descoberta inesperada provoca curiosidade, o produto é revelado como a descoberta, demonstrado e justificado. Não deve parecer uma história falsa excessivamente dramática.",
    category: "storytelling",
    trendStatus: "steady",
    bestFor: [
      "Beleza",
      "Organização",
      "Cozinha",
      "Gadgets",
      "Produtos de cuidado pessoal",
      "Produtos que resolvem frustração cotidiana",
    ],
    avoidFor: ["Produtos de uso muito específico sem contexto cotidiano", "Produtos com benefícios técnicos abstratos"],
    requiredInputs: ["Narrativa de situação", "Produto físico ou fotos"],
    supportsAI: true,
    requiresRealProduct: false,
    requiresRealPerson: false,
    supportsNoSpeak: false,
    difficulty: "medium",
    trustLevel: 3,
    complianceRisk: "low",
    veoCompatibility: "full",
    defaultDuration: 35,
    sceneStructure: [
      "Situação cotidiana",
      "Descoberta inesperada",
      "Curiosidade",
      "Produto revelado",
      "Demonstração",
      "Motivo para comprar",
      "CTA",
    ],
    promptRules: [
      "Story must feel natural and relatable",
      "Avoid overly dramatic or theatrical narrative",
      "Product discovery must feel organic",
    ],
    negativePromptRules: ["no overly dramatic acting", "no fake backstory", "no scripted surprise"],
    badges: ["proven_trend", "ai_compatible", "low_risk"],
  },

  // ─── Roteiro para LIVE ────────────────────────────────────────────────────────
  {
    id: "live_sales_script",
    name: "Roteiro para LIVE",
    shortDescription: "Script completo para transmissão ao vivo no TikTok Shop.",
    fullDescription:
      "Gera um roteiro estruturado para LIVE de vendas no TikTok Shop. Inclui abertura, apresentação, demonstração, perguntas para o público, respostas a objeções, repetição estratégica, urgência permitida, blocos de CTA e momentos de recap. Blocos são reutilizáveis e intercambiáveis.",
    category: "live",
    trendStatus: "proven",
    bestFor: [
      "Todos os produtos",
      "Especialmente: kits, promoções, lançamentos",
      "Queima de estoque",
      "Produtos com demonstração ao vivo",
    ],
    avoidFor: ["Conteúdo gravado (este formato é exclusivo para LIVE)"],
    requiredInputs: ["Produto físico", "Roteiro de abertura", "Lista de objeções comuns"],
    supportsAI: false,
    requiresRealProduct: true,
    requiresRealPerson: true,
    supportsNoSpeak: false,
    difficulty: "high",
    trustLevel: 5,
    complianceRisk: "medium",
    veoCompatibility: "not_recommended",
    defaultDuration: 1800, // 30 minutos
    sceneStructure: [
      "Abertura e boas-vindas",
      "Apresentação do produto",
      "Demonstração",
      "Perguntas para o público",
      "Respostas às objeções",
      "Repetição estratégica",
      "Urgência permitida",
      "CTA principal",
      "Blocos de recap",
      "Encerramento",
    ],
    promptRules: [
      "Each block must be modular and reusable",
      "Urgency must be real (limited stock, time-limited offer), not fabricated",
      "Engagement questions must be natural",
      "Objection responses must be honest",
    ],
    negativePromptRules: [
      "no fake countdown urgency",
      "no invented scarcity",
      "no testimonials the creator cannot verify",
    ],
    badges: ["high_conversion", "proven_trend", "high_trust", "compliance_attention"],
    warningWhenNoPhysicalProduct: true,
  },
];

/** Retorna um formato pelo ID. */
export function getFormatById(id: string): ScriptFormatDefinition | undefined {
  return SCRIPT_FORMATS.find((f) => f.id === id);
}

/** Retorna todos os formatos de uma categoria. */
export function getFormatsByCategory(category: string): ScriptFormatDefinition[] {
  return SCRIPT_FORMATS.filter((f) => f.category === category);
}
