/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedAiVideoGeneratorRouteImport } from './routes/_authenticated/ai-video-generator'
import { Route as AuthenticatedAutoClipsRouteImport } from './routes/_authenticated/auto-clips'
import { Route as AuthenticatedAvatarsRouteImport } from './routes/_authenticated/avatars'
import { Route as AuthenticatedCharactersRouteImport } from './routes/_authenticated/characters'
import { Route as AuthenticatedCopiesRouteImport } from './routes/_authenticated/copies'
import { Route as AuthenticatedCopyModelerRouteImport } from './routes/_authenticated/copy-modeler'
import { Route as AuthenticatedCreativeLabRouteImport } from './routes/_authenticated/creative-lab'
import { Route as AuthenticatedCreativeTrackerRouteImport } from './routes/_authenticated/creative-tracker'
import { Route as AuthenticatedDailyStudioRouteImport } from './routes/_authenticated/daily-studio'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHookStudioRouteImport } from './routes/_authenticated/hook-studio'
import { Route as AuthenticatedLiveScriptsRouteImport } from './routes/_authenticated/live-scripts'
import { Route as AuthenticatedMetadataCleanerRouteImport } from './routes/_authenticated/metadata-cleaner'
import { Route as AuthenticatedMovementsRouteImport } from './routes/_authenticated/movements'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedProductionAgentRouteImport } from './routes/_authenticated/production-agent'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedRadarRouteImport } from './routes/_authenticated/radar'
import { Route as AuthenticatedScenariosRouteImport } from './routes/_authenticated/scenarios'
import { Route as AuthenticatedTiktokDownloaderRouteImport } from './routes/_authenticated/tiktok-downloader'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedVideoCombinerRouteImport } from './routes/_authenticated/video-combiner'
import { Route as AuthenticatedVideoEditorRouteImport } from './routes/_authenticated/video-editor'
import { Route as AuthenticatedVideoTranscriberRouteImport } from './routes/_authenticated/video-transcriber'
import { Route as AuthenticatedViralAuditRouteImport } from './routes/_authenticated/viral-audit'
import { Route as AuthenticatedVoiceStudioRouteImport } from './routes/_authenticated/voice-studio'
import { Route as AuthenticatedWatermarkRemoverRouteImport } from './routes/_authenticated/watermark-remover'
import { Route as AuthenticatedAdminVideoProvidersRouteImport } from './routes/_authenticated/admin/video-providers'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects/new'
import { Route as AuthTiktokCallbackRouteImport } from './routes/auth/tiktok/callback'
import { Route as ApiAuthTiktokStartRouteImport } from './routes/api/auth/tiktok/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiVideoGeneratorRoute =
  AuthenticatedAiVideoGeneratorRouteImport.update({
    id: '/ai-video-generator',
    path: '/ai-video-generator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutoClipsRoute = AuthenticatedAutoClipsRouteImport.update({
  id: '/auto-clips',
  path: '/auto-clips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvatarsRoute = AuthenticatedAvatarsRouteImport.update({
  id: '/avatars',
  path: '/avatars',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCharactersRoute = AuthenticatedCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopiesRoute = AuthenticatedCopiesRouteImport.update({
  id: '/copies',
  path: '/copies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopyModelerRoute =
  AuthenticatedCopyModelerRouteImport.update({
    id: '/copy-modeler',
    path: '/copy-modeler',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreativeLabRoute =
  AuthenticatedCreativeLabRouteImport.update({
    id: '/creative-lab',
    path: '/creative-lab',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreativeTrackerRoute =
  AuthenticatedCreativeTrackerRouteImport.update({
    id: '/creative-tracker',
    path: '/creative-tracker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDailyStudioRoute =
  AuthenticatedDailyStudioRouteImport.update({
    id: '/daily-studio',
    path: '/daily-studio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHookStudioRoute = AuthenticatedHookStudioRouteImport.update({
  id: '/hook-studio',
  path: '/hook-studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveScriptsRoute =
  AuthenticatedLiveScriptsRouteImport.update({
    id: '/live-scripts',
    path: '/live-scripts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetadataCleanerRoute =
  AuthenticatedMetadataCleanerRouteImport.update({
    id: '/metadata-cleaner',
    path: '/metadata-cleaner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMovementsRoute = AuthenticatedMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionAgentRoute =
  AuthenticatedProductionAgentRouteImport.update({
    id: '/production-agent',
    path: '/production-agent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRadarRoute = AuthenticatedRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScenariosRoute = AuthenticatedScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTiktokDownloaderRoute =
  AuthenticatedTiktokDownloaderRouteImport.update({
    id: '/tiktok-downloader',
    path: '/tiktok-downloader',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVideoCombinerRoute =
  AuthenticatedVideoCombinerRouteImport.update({
    id: '/video-combiner',
    path: '/video-combiner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVideoEditorRoute =
  AuthenticatedVideoEditorRouteImport.update({
    id: '/video-editor',
    path: '/video-editor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVideoTranscriberRoute =
  AuthenticatedVideoTranscriberRouteImport.update({
    id: '/video-transcriber',
    path: '/video-transcriber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedViralAuditRoute = AuthenticatedViralAuditRouteImport.update({
  id: '/viral-audit',
  path: '/viral-audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVoiceStudioRoute =
  AuthenticatedVoiceStudioRouteImport.update({
    id: '/voice-studio',
    path: '/voice-studio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWatermarkRemoverRoute =
  AuthenticatedWatermarkRemoverRouteImport.update({
    id: '/watermark-remover',
    path: '/watermark-remover',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVideoProvidersRoute =
  AuthenticatedAdminVideoProvidersRouteImport.update({
    id: '/admin/video-providers',
    path: '/admin/video-providers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthTiktokCallbackRoute = AuthTiktokCallbackRouteImport.update({
  id: '/auth/tiktok/callback',
  path: '/auth/tiktok/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTiktokStartRoute = ApiAuthTiktokStartRouteImport.update({
  id: '/api/auth/tiktok/start',
  path: '/api/auth/tiktok/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/ai-video-generator': typeof AuthenticatedAiVideoGeneratorRoute
  '/auto-clips': typeof AuthenticatedAutoClipsRoute
  '/avatars': typeof AuthenticatedAvatarsRoute
  '/characters': typeof AuthenticatedCharactersRoute
  '/copies': typeof AuthenticatedCopiesRoute
  '/copy-modeler': typeof AuthenticatedCopyModelerRoute
  '/creative-lab': typeof AuthenticatedCreativeLabRoute
  '/creative-tracker': typeof AuthenticatedCreativeTrackerRoute
  '/daily-studio': typeof AuthenticatedDailyStudioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hook-studio': typeof AuthenticatedHookStudioRoute
  '/live-scripts': typeof AuthenticatedLiveScriptsRoute
  '/metadata-cleaner': typeof AuthenticatedMetadataCleanerRoute
  '/movements': typeof AuthenticatedMovementsRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/production-agent': typeof AuthenticatedProductionAgentRoute
  '/products': typeof AuthenticatedProductsRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/scenarios': typeof AuthenticatedScenariosRoute
  '/tiktok-downloader': typeof AuthenticatedTiktokDownloaderRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/video-combiner': typeof AuthenticatedVideoCombinerRoute
  '/video-editor': typeof AuthenticatedVideoEditorRoute
  '/video-transcriber': typeof AuthenticatedVideoTranscriberRoute
  '/viral-audit': typeof AuthenticatedViralAuditRoute
  '/voice-studio': typeof AuthenticatedVoiceStudioRoute
  '/watermark-remover': typeof AuthenticatedWatermarkRemoverRoute
  '/admin/video-providers': typeof AuthenticatedAdminVideoProvidersRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/auth/tiktok/callback': typeof AuthTiktokCallbackRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/auth/tiktok/start': typeof ApiAuthTiktokStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/ai-video-generator': typeof AuthenticatedAiVideoGeneratorRoute
  '/auto-clips': typeof AuthenticatedAutoClipsRoute
  '/avatars': typeof AuthenticatedAvatarsRoute
  '/characters': typeof AuthenticatedCharactersRoute
  '/copies': typeof AuthenticatedCopiesRoute
  '/copy-modeler': typeof AuthenticatedCopyModelerRoute
  '/creative-lab': typeof AuthenticatedCreativeLabRoute
  '/creative-tracker': typeof AuthenticatedCreativeTrackerRoute
  '/daily-studio': typeof AuthenticatedDailyStudioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hook-studio': typeof AuthenticatedHookStudioRoute
  '/live-scripts': typeof AuthenticatedLiveScriptsRoute
  '/metadata-cleaner': typeof AuthenticatedMetadataCleanerRoute
  '/movements': typeof AuthenticatedMovementsRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/production-agent': typeof AuthenticatedProductionAgentRoute
  '/products': typeof AuthenticatedProductsRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/scenarios': typeof AuthenticatedScenariosRoute
  '/tiktok-downloader': typeof AuthenticatedTiktokDownloaderRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/video-combiner': typeof AuthenticatedVideoCombinerRoute
  '/video-editor': typeof AuthenticatedVideoEditorRoute
  '/video-transcriber': typeof AuthenticatedVideoTranscriberRoute
  '/viral-audit': typeof AuthenticatedViralAuditRoute
  '/voice-studio': typeof AuthenticatedVoiceStudioRoute
  '/watermark-remover': typeof AuthenticatedWatermarkRemoverRoute
  '/admin/video-providers': typeof AuthenticatedAdminVideoProvidersRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/auth/tiktok/callback': typeof AuthTiktokCallbackRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/api/auth/tiktok/start': typeof ApiAuthTiktokStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_authenticated/ai-video-generator': typeof AuthenticatedAiVideoGeneratorRoute
  '/_authenticated/auto-clips': typeof AuthenticatedAutoClipsRoute
  '/_authenticated/avatars': typeof AuthenticatedAvatarsRoute
  '/_authenticated/characters': typeof AuthenticatedCharactersRoute
  '/_authenticated/copies': typeof AuthenticatedCopiesRoute
  '/_authenticated/copy-modeler': typeof AuthenticatedCopyModelerRoute
  '/_authenticated/creative-lab': typeof AuthenticatedCreativeLabRoute
  '/_authenticated/creative-tracker': typeof AuthenticatedCreativeTrackerRoute
  '/_authenticated/daily-studio': typeof AuthenticatedDailyStudioRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hook-studio': typeof AuthenticatedHookStudioRoute
  '/_authenticated/live-scripts': typeof AuthenticatedLiveScriptsRoute
  '/_authenticated/metadata-cleaner': typeof AuthenticatedMetadataCleanerRoute
  '/_authenticated/movements': typeof AuthenticatedMovementsRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/production-agent': typeof AuthenticatedProductionAgentRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/radar': typeof AuthenticatedRadarRoute
  '/_authenticated/scenarios': typeof AuthenticatedScenariosRoute
  '/_authenticated/tiktok-downloader': typeof AuthenticatedTiktokDownloaderRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/video-combiner': typeof AuthenticatedVideoCombinerRoute
  '/_authenticated/video-editor': typeof AuthenticatedVideoEditorRoute
  '/_authenticated/video-transcriber': typeof AuthenticatedVideoTranscriberRoute
  '/_authenticated/viral-audit': typeof AuthenticatedViralAuditRoute
  '/_authenticated/voice-studio': typeof AuthenticatedVoiceStudioRoute
  '/_authenticated/watermark-remover': typeof AuthenticatedWatermarkRemoverRoute
  '/_authenticated/admin/video-providers': typeof AuthenticatedAdminVideoProvidersRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/auth/tiktok/callback': typeof AuthTiktokCallbackRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/auth/tiktok/start': typeof ApiAuthTiktokStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/ai-video-generator'
    | '/auto-clips'
    | '/avatars'
    | '/characters'
    | '/copies'
    | '/copy-modeler'
    | '/creative-lab'
    | '/creative-tracker'
    | '/daily-studio'
    | '/dashboard'
    | '/hook-studio'
    | '/live-scripts'
    | '/metadata-cleaner'
    | '/movements'
    | '/performance'
    | '/production-agent'
    | '/products'
    | '/radar'
    | '/scenarios'
    | '/tiktok-downloader'
    | '/tools'
    | '/video-combiner'
    | '/video-editor'
    | '/video-transcriber'
    | '/viral-audit'
    | '/voice-studio'
    | '/watermark-remover'
    | '/admin/video-providers'
    | '/projects/$projectId'
    | '/projects/new'
    | '/auth/tiktok/callback'
    | '/projects/'
    | '/api/auth/tiktok/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/ai-video-generator'
    | '/auto-clips'
    | '/avatars'
    | '/characters'
    | '/copies'
    | '/copy-modeler'
    | '/creative-lab'
    | '/creative-tracker'
    | '/daily-studio'
    | '/dashboard'
    | '/hook-studio'
    | '/live-scripts'
    | '/metadata-cleaner'
    | '/movements'
    | '/performance'
    | '/production-agent'
    | '/products'
    | '/radar'
    | '/scenarios'
    | '/tiktok-downloader'
    | '/tools'
    | '/video-combiner'
    | '/video-editor'
    | '/video-transcriber'
    | '/viral-audit'
    | '/voice-studio'
    | '/watermark-remover'
    | '/admin/video-providers'
    | '/projects/$projectId'
    | '/projects/new'
    | '/auth/tiktok/callback'
    | '/projects'
    | '/api/auth/tiktok/start'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/_authenticated/ai-video-generator'
    | '/_authenticated/auto-clips'
    | '/_authenticated/avatars'
    | '/_authenticated/characters'
    | '/_authenticated/copies'
    | '/_authenticated/copy-modeler'
    | '/_authenticated/creative-lab'
    | '/_authenticated/creative-tracker'
    | '/_authenticated/daily-studio'
    | '/_authenticated/dashboard'
    | '/_authenticated/hook-studio'
    | '/_authenticated/live-scripts'
    | '/_authenticated/metadata-cleaner'
    | '/_authenticated/movements'
    | '/_authenticated/performance'
    | '/_authenticated/production-agent'
    | '/_authenticated/products'
    | '/_authenticated/radar'
    | '/_authenticated/scenarios'
    | '/_authenticated/tiktok-downloader'
    | '/_authenticated/tools'
    | '/_authenticated/video-combiner'
    | '/_authenticated/video-editor'
    | '/_authenticated/video-transcriber'
    | '/_authenticated/viral-audit'
    | '/_authenticated/voice-studio'
    | '/_authenticated/watermark-remover'
    | '/_authenticated/admin/video-providers'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/new'
    | '/auth/tiktok/callback'
    | '/_authenticated/projects/'
    | '/api/auth/tiktok/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  AuthTiktokCallbackRoute: typeof AuthTiktokCallbackRoute
  ApiAuthTiktokStartRoute: typeof ApiAuthTiktokStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-video-generator': {
      id: '/_authenticated/ai-video-generator'
      path: '/ai-video-generator'
      fullPath: '/ai-video-generator'
      preLoaderRoute: typeof AuthenticatedAiVideoGeneratorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auto-clips': {
      id: '/_authenticated/auto-clips'
      path: '/auto-clips'
      fullPath: '/auto-clips'
      preLoaderRoute: typeof AuthenticatedAutoClipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avatars': {
      id: '/_authenticated/avatars'
      path: '/avatars'
      fullPath: '/avatars'
      preLoaderRoute: typeof AuthenticatedAvatarsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/characters': {
      id: '/_authenticated/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof AuthenticatedCharactersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copies': {
      id: '/_authenticated/copies'
      path: '/copies'
      fullPath: '/copies'
      preLoaderRoute: typeof AuthenticatedCopiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copy-modeler': {
      id: '/_authenticated/copy-modeler'
      path: '/copy-modeler'
      fullPath: '/copy-modeler'
      preLoaderRoute: typeof AuthenticatedCopyModelerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creative-lab': {
      id: '/_authenticated/creative-lab'
      path: '/creative-lab'
      fullPath: '/creative-lab'
      preLoaderRoute: typeof AuthenticatedCreativeLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creative-tracker': {
      id: '/_authenticated/creative-tracker'
      path: '/creative-tracker'
      fullPath: '/creative-tracker'
      preLoaderRoute: typeof AuthenticatedCreativeTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-studio': {
      id: '/_authenticated/daily-studio'
      path: '/daily-studio'
      fullPath: '/daily-studio'
      preLoaderRoute: typeof AuthenticatedDailyStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hook-studio': {
      id: '/_authenticated/hook-studio'
      path: '/hook-studio'
      fullPath: '/hook-studio'
      preLoaderRoute: typeof AuthenticatedHookStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-scripts': {
      id: '/_authenticated/live-scripts'
      path: '/live-scripts'
      fullPath: '/live-scripts'
      preLoaderRoute: typeof AuthenticatedLiveScriptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metadata-cleaner': {
      id: '/_authenticated/metadata-cleaner'
      path: '/metadata-cleaner'
      fullPath: '/metadata-cleaner'
      preLoaderRoute: typeof AuthenticatedMetadataCleanerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movements': {
      id: '/_authenticated/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof AuthenticatedMovementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production-agent': {
      id: '/_authenticated/production-agent'
      path: '/production-agent'
      fullPath: '/production-agent'
      preLoaderRoute: typeof AuthenticatedProductionAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar': {
      id: '/_authenticated/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AuthenticatedRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scenarios': {
      id: '/_authenticated/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof AuthenticatedScenariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tiktok-downloader': {
      id: '/_authenticated/tiktok-downloader'
      path: '/tiktok-downloader'
      fullPath: '/tiktok-downloader'
      preLoaderRoute: typeof AuthenticatedTiktokDownloaderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/video-combiner': {
      id: '/_authenticated/video-combiner'
      path: '/video-combiner'
      fullPath: '/video-combiner'
      preLoaderRoute: typeof AuthenticatedVideoCombinerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/video-editor': {
      id: '/_authenticated/video-editor'
      path: '/video-editor'
      fullPath: '/video-editor'
      preLoaderRoute: typeof AuthenticatedVideoEditorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/video-transcriber': {
      id: '/_authenticated/video-transcriber'
      path: '/video-transcriber'
      fullPath: '/video-transcriber'
      preLoaderRoute: typeof AuthenticatedVideoTranscriberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/viral-audit': {
      id: '/_authenticated/viral-audit'
      path: '/viral-audit'
      fullPath: '/viral-audit'
      preLoaderRoute: typeof AuthenticatedViralAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/voice-studio': {
      id: '/_authenticated/voice-studio'
      path: '/voice-studio'
      fullPath: '/voice-studio'
      preLoaderRoute: typeof AuthenticatedVoiceStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watermark-remover': {
      id: '/_authenticated/watermark-remover'
      path: '/watermark-remover'
      fullPath: '/watermark-remover'
      preLoaderRoute: typeof AuthenticatedWatermarkRemoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/video-providers': {
      id: '/_authenticated/admin/video-providers'
      path: '/admin/video-providers'
      fullPath: '/admin/video-providers'
      preLoaderRoute: typeof AuthenticatedAdminVideoProvidersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/tiktok/callback': {
      id: '/auth/tiktok/callback'
      path: '/auth/tiktok/callback'
      fullPath: '/auth/tiktok/callback'
      preLoaderRoute: typeof AuthTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/tiktok/start': {
      id: '/api/auth/tiktok/start'
      path: '/api/auth/tiktok/start'
      fullPath: '/api/auth/tiktok/start'
      preLoaderRoute: typeof ApiAuthTiktokStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiVideoGeneratorRoute: typeof AuthenticatedAiVideoGeneratorRoute
  AuthenticatedAutoClipsRoute: typeof AuthenticatedAutoClipsRoute
  AuthenticatedAvatarsRoute: typeof AuthenticatedAvatarsRoute
  AuthenticatedCharactersRoute: typeof AuthenticatedCharactersRoute
  AuthenticatedCopiesRoute: typeof AuthenticatedCopiesRoute
  AuthenticatedCopyModelerRoute: typeof AuthenticatedCopyModelerRoute
  AuthenticatedCreativeLabRoute: typeof AuthenticatedCreativeLabRoute
  AuthenticatedCreativeTrackerRoute: typeof AuthenticatedCreativeTrackerRoute
  AuthenticatedDailyStudioRoute: typeof AuthenticatedDailyStudioRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHookStudioRoute: typeof AuthenticatedHookStudioRoute
  AuthenticatedLiveScriptsRoute: typeof AuthenticatedLiveScriptsRoute
  AuthenticatedMetadataCleanerRoute: typeof AuthenticatedMetadataCleanerRoute
  AuthenticatedMovementsRoute: typeof AuthenticatedMovementsRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedProductionAgentRoute: typeof AuthenticatedProductionAgentRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedRadarRoute: typeof AuthenticatedRadarRoute
  AuthenticatedScenariosRoute: typeof AuthenticatedScenariosRoute
  AuthenticatedTiktokDownloaderRoute: typeof AuthenticatedTiktokDownloaderRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedVideoCombinerRoute: typeof AuthenticatedVideoCombinerRoute
  AuthenticatedVideoEditorRoute: typeof AuthenticatedVideoEditorRoute
  AuthenticatedVideoTranscriberRoute: typeof AuthenticatedVideoTranscriberRoute
  AuthenticatedViralAuditRoute: typeof AuthenticatedViralAuditRoute
  AuthenticatedVoiceStudioRoute: typeof AuthenticatedVoiceStudioRoute
  AuthenticatedWatermarkRemoverRoute: typeof AuthenticatedWatermarkRemoverRoute
  AuthenticatedAdminVideoProvidersRoute: typeof AuthenticatedAdminVideoProvidersRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiVideoGeneratorRoute: AuthenticatedAiVideoGeneratorRoute,
  AuthenticatedAutoClipsRoute: AuthenticatedAutoClipsRoute,
  AuthenticatedAvatarsRoute: AuthenticatedAvatarsRoute,
  AuthenticatedCharactersRoute: AuthenticatedCharactersRoute,
  AuthenticatedCopiesRoute: AuthenticatedCopiesRoute,
  AuthenticatedCopyModelerRoute: AuthenticatedCopyModelerRoute,
  AuthenticatedCreativeLabRoute: AuthenticatedCreativeLabRoute,
  AuthenticatedCreativeTrackerRoute: AuthenticatedCreativeTrackerRoute,
  AuthenticatedDailyStudioRoute: AuthenticatedDailyStudioRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHookStudioRoute: AuthenticatedHookStudioRoute,
  AuthenticatedLiveScriptsRoute: AuthenticatedLiveScriptsRoute,
  AuthenticatedMetadataCleanerRoute: AuthenticatedMetadataCleanerRoute,
  AuthenticatedMovementsRoute: AuthenticatedMovementsRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedProductionAgentRoute: AuthenticatedProductionAgentRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedRadarRoute: AuthenticatedRadarRoute,
  AuthenticatedScenariosRoute: AuthenticatedScenariosRoute,
  AuthenticatedTiktokDownloaderRoute: AuthenticatedTiktokDownloaderRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedVideoCombinerRoute: AuthenticatedVideoCombinerRoute,
  AuthenticatedVideoEditorRoute: AuthenticatedVideoEditorRoute,
  AuthenticatedVideoTranscriberRoute: AuthenticatedVideoTranscriberRoute,
  AuthenticatedViralAuditRoute: AuthenticatedViralAuditRoute,
  AuthenticatedVoiceStudioRoute: AuthenticatedVoiceStudioRoute,
  AuthenticatedWatermarkRemoverRoute: AuthenticatedWatermarkRemoverRoute,
  AuthenticatedAdminVideoProvidersRoute: AuthenticatedAdminVideoProvidersRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  AuthTiktokCallbackRoute: AuthTiktokCallbackRoute,
  ApiAuthTiktokStartRoute: ApiAuthTiktokStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
